---
- name: Check if kubeconfig is already created
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.kube/config"
  register: kubeconfig_check

- name: Copy kubeconfig
  when: not kubeconfig_check.stat.exists
  block:
    - name: Create .kube directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: "0644"

    - name: Copy admin.conf to user's kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_env.HOME }}/.kube/config"
        remote_src: true
        mode: "0600"

    - name: Set owner of kube config file
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube/config"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
