"type: build ⚙️":
  title: '^build(\(.+\))?:.*'
"type: ci ⚙️":
  title: '^ci(\(.+\))?:.*'
"type: chore 🧹":
  title: '^chore(\(.+\))?:.*'
"type: docs 📝":
  title: '^docs(\(.+\))?:.*'
"type: feat ✨":
  title: '^feat(\(.+\))?:.*'
"type: fix 🐛":
  title: '^fix(\(.+\))?:.*'
"type: perf 🚀":
  title: '^perf(\(.+\))?:.*'
"type: refactor 🔨":
  title: '^refactor(\(.+\))?:.*'
"type: revert ⏪️":
  title: '^revert(\(.+\))?:.*'
"type: style 🎨":
  title: '^style(\(.+\))?:.*'
"type: test 🧪":
  title: '^test(\(.+\))?:.*'
