---
- name: Check cloud-init image list
  ansible.builtin.command: "qm list"
  register: qm_list
  changed_when: false

- name: Build template
  when: "template_name not in qm_list.stdout"
  block:
    - name: Download cloud image
      ansible.builtin.get_url:
        url: "{{ cloud_image_url }}"
        dest: "{{ cloud_image_path }}"
        mode: "0700"

    - name: Create a VM to use as a template
      ansible.builtin.command: "qm create {{ template_id }} --name {{ template_name }} --memory {{ template_memory }} --net0 virtio,bridge=vmbr0"
      changed_when: false
      become: true

    - name: Import disk image
      ansible.builtin.command: "qm importdisk {{ template_id }} {{ cloud_image_path }} local-lvm"
      changed_when: false
      become: true

    - name: Configure VM to use imported image
      ansible.builtin.command: "qm set {{ template_id }} --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-{{ template_id }}-disk-0"
      changed_when: false
      become: true

    - name: Add cloud-init image as CDROM
      ansible.builtin.command: "qm set {{ template_id }} --ide2 local-lvm:cloudinit"
      changed_when: false
      become: true

    - name: Configure boot from the image
      ansible.builtin.command: "qm set {{ template_id }} --boot c --bootdisk scsi0"
      changed_when: false
      become: true

    - name: Attach serial console
      ansible.builtin.command: "qm set {{ template_id }} --serial0 socket --vga serial0"
      changed_when: false
      become: true

    - name: Create template
      ansible.builtin.command: "qm template {{ template_id }}"
      changed_when: false
      become: true
