---
- name: Check if kubeadm is already initialised
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_admin_check

- name: Initialise kubeadm
  when: not kubernetes_admin_check.stat.exists
  block:
    - name: Create kubeadm-config.yaml file from template
      ansible.builtin.template:
        src: kubeadm-config.yaml.j2
        dest: /root/kubeadm-config.yaml
        mode: "0644"

    - name: Run kubeadm init with config file and upload certs
      ansible.builtin.command: kubeadm init --config /root/kubeadm-config.yaml --upload-certs
      register: kubeadm_init
      changed_when: kubeadm_init.rc != 0

    - name: Run command on master node
      ansible.builtin.shell: |
        echo $(kubeadm token create --print-join-command) \
        --control-plane --apiserver-bind-port=6443 \
        --certificate-key $(kubeadm init phase upload-certs --upload-certs | grep -vw -e certificate -e Namespace)
      register: kubeadm_join_command
      changed_when: kubeadm_join_command.rc != 0

- name: Include copy-kubeconfig role
  ansible.builtin.include_role:
    name: copy-kubeconfig

- name: Check if kubeadm-config has controlPlaneEndpoint configured
  ansible.builtin.shell: >-
    set -o pipefail && kubectl -n kube-system get configmap kubeadm-config -o jsonpath='{.data.ClusterConfiguration}'
    | grep -q 'controlPlaneEndpoint: {{ ansible_host }}:6443'
  args:
    executable: /bin/bash
  register: check_control_plane_endpoint
  changed_when: false
  ignore_errors: true

- name: Update kubeadm-config
  when: check_control_plane_endpoint.rc != 0
  block:
    - name: Update kubeadm-config configmap
      ansible.builtin.shell: >
        kubectl -n kube-system get configmap kubeadm-config -o json |
        jq 'if (.data.ClusterConfiguration | contains("controlPlaneEndpoint")) then
        .data.ClusterConfiguration |= sub("controlPlaneEndpoint: .*"; "controlPlaneEndpoint: {{ ansible_host }}:6443")
        else .data.ClusterConfiguration |= . + "\ncontrolPlaneEndpoint: {{ ansible_host }}:6443" end' |
        kubectl apply -f -
      changed_when: false
