---
- hosts: all
  name: Set up Kubernetes components
  pre_tasks:
    - name: Gather service state information as fact data
      ansible.builtin.service_facts:
    # - name: Print service facts
    #   ansible.builtin.debug:
    #     var: ansible_facts.services
  roles:
    - bootstrap-node
    - install-runc
    - install-cni
    - configure-containerd
    - install-nerdctl
    - install-crictl
    - configure-kubeadm-kubelet
    - install-kubectl
    - download-cilium

- hosts: primary_nodes
  name: Initialize Kubernetes control plane on primary node
  roles:
    - init-kubeadm

- hosts: secondary_nodes
  name: Join Kubernetes control plane on secondary nodes
  roles:
    - join-kubeadm

- hosts: primary_nodes
  name: Perform post-processing tasks after setting up Kubernetes
  roles:
    - install-cilium
