---
- name: Check if kubectl exists
  ansible.builtin.stat:
    path: /usr/local/sbin/kubectl
  register: kubectl_file

- name: Install kubectl
  when: not kubectl_file.stat.exists
  block:
    - name: Download kubectl
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
        dest: /usr/local/sbin/kubectl
        mode: "0755"
