name: Label PRs
on:
  - pull_request
jobs:
  label:
    name: "Label PR based on title"
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@v1.11
        env:
          GITHUB_TOKEN: "${{ secrets.LABELER_TOKEN }}"
