---
- name: Check if cilium is already installed
  ansible.builtin.stat:
    path: "/usr/local/bin/cilium"
  register: cilium_check

- name: Install cilium
  when: not cilium_check.stat.exists
  block:
    - name: Download Cilium CLI
      ansible.builtin.get_url:
        url: https://github.com/cilium/cilium-cli/releases/download/v0.13.0/cilium-linux-amd64.tar.gz
        dest: /tmp/cilium-linux-amd64.tar.gz
        mode: "0644"

    - name: Extract Cilium CLI
      ansible.builtin.unarchive:
        src: /tmp/cilium-linux-amd64.tar.gz
        dest: /usr/local/bin/
        remote_src: true

    - name: Install Cilium
      ansible.builtin.command: cilium install
      register: cilium_install
      changed_when: cilium_install.rc != 0
      when: "'primary_nodes' in group_names"

    - name: Wait for Cilium status to be ready
      ansible.builtin.command: cilium status --wait
      register: cilium_status
      changed_when: cilium_status.rc != 0
      when: "'primary_nodes' in group_names"
